### Test the home page endpoint

GET http://localhost:3001

### Test a 404
GET http://localhost:3001/testing-404

### Test creating a product
POST http://localhost:3001/
Content-Type: application/json

{
  "title": "Golf shirts"
}

### Test the PUT which should change a product

PUT http://localhost:3001/5f2b52aa31da883108c723cb
Content-Type: application/json

{
  "title": "Testing"
}

### Logos

GET http://localhost:3001/logos

### Products

GET http://localhost:3001/products
